### ISSUE TITLE
Bug: Swift SDK mixes up conversation without conversationId / conversations with empty conversationId

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-ios#145]
### Describe the bug

In the JS SDK, these return different conversations (different topics):

```
const convo1 = await xmtpClient.conversations.newConversation(
    "0x305DAfc577579c08109c9b732C78f192cCA952fd"
  );
  const convo2 = await xmtpClient.conversations.newConversation(
    "0x305DAfc577579c08109c9b732C78f192cCA952fd",
    { conversationId: "", metadata: {} }
  );
```

Convo 1 has `convo1.context = undefined` while `convo2.context = {conversationId: "", metadata: {}}`

But in Swift, if I get back the conversations from the same private key, I have no way to differentiate them from their conversationId.
Indeed the Swift SDK will return the both of them with `context = {conversationId: "", metadata: {}}` because of this line:
https://github.com/xmtp/xmtp-ios/blob/main/Sources/XMTP/ConversationV2.swift#L21

### Expected behavior

I should be able to differentiate a conversation with an empty string for conversation Id from a conversation without any context in Swift

**Comment by nplasterer** [comment]
I think this should be fixed in the latest release that fixes a deterministic topics bug allowing duplicate conversations across all SDKs. After diving in the code mentioned above is actually stale and not used and the issue seemed to be related to how we do deterministic topics. Please feel free to reopen if that is not the case. I'd also advise updating the JS SDK as well.
